apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: flower
  name: flower-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: flower
    spec:
      containers:
      - image: flower-test
        name: flower
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
