apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: username
          - name: RABBITMQ_DEFAULT_PASS
            value: password
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
